build:
  hooks:
    pre-assets:
      - 'SHOPWARE_SKIP_ENTITY_SCHEMA_DUMP=1 bin/build-administration.sh'
      - 'mkdir -p public/bundles/administration/administration'
      - 'cp -R vendor/shopware/platform/src/Administration/Resources/public/administration/. public/bundles/administration/administration/'
