app:
  php:
    version: "8.4"
  environment_variables:
    - name: APP_ENV
      value: "production"
      scope: RUN
    - name: K8S_CACHE_HOST
      value: "redis"
      scope: RUN
    - name: PHP_SESSION_SAVE_PATH
      value: "tcp://redis:6379"
      scope: RUN
    - name: MESSENGER_TRANSPORT_DSN
      value: "redis://redis:6379/messages/symfony/?auto_setup=true&serializer=1&stream_max_entries=0&dbindex=0"
      scope: RUN
services:
  mysql:
    version: "8.0"
  redis:
    version: "7.0"
  opensearch:
    enabled: false
